/*
 * This file is generated by jOOQ.
 */
package supplement;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import supplement.tables.FlywaySchemaHistory;
import supplement.tables.SupplementGroup;
import supplement.tables.Supplements;
import supplement.tables.records.FlywaySchemaHistoryRecord;
import supplement.tables.records.SupplementGroupRecord;
import supplement.tables.records.SupplementsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<SupplementGroupRecord> SUPPLEMENT_GROUP_PKEY = Internal.createUniqueKey(SupplementGroup.SUPPLEMENT_GROUP, DSL.name("supplement_group_pkey"), new TableField[] { SupplementGroup.SUPPLEMENT_GROUP.NAME }, true);
    public static final UniqueKey<SupplementsRecord> SUPPLEMENTS_PKEY = Internal.createUniqueKey(Supplements.SUPPLEMENTS, DSL.name("supplements_pkey"), new TableField[] { Supplements.SUPPLEMENTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SupplementsRecord, SupplementGroupRecord> SUPPLEMENTS__SUPPLEMENTS_GROUP_NAME_FKEY = Internal.createForeignKey(Supplements.SUPPLEMENTS, DSL.name("supplements_group_name_fkey"), new TableField[] { Supplements.SUPPLEMENTS.GROUP_NAME }, Keys.SUPPLEMENT_GROUP_PKEY, new TableField[] { SupplementGroup.SUPPLEMENT_GROUP.NAME }, true);
}
