/*
 * This file is generated by jOOQ.
 */
package supplement;


import supplement.tables.FlywaySchemaHistory;
import supplement.tables.SupplementGroup;
import supplement.tables.Supplements;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * サプリメントグループテーブル
     */
    public static final SupplementGroup SUPPLEMENT_GROUP = SupplementGroup.SUPPLEMENT_GROUP;

    /**
     * サプリメントテーブル
     */
    public static final Supplements SUPPLEMENTS = Supplements.SUPPLEMENTS;
}
