spring:
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
    cors:
        allowed-origins:
            - ${FRONTEND_URL}
    server:
        port: ${PORT:8080}
