/*
 * This file is generated by jOOQ.
 */
package supplement.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import supplement.tables.Supplements;


/**
 * サプリメントテーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplementsRecord extends UpdatableRecordImpl<SupplementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.supplements.id</code>. サプリメントID
     */
    public SupplementsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.supplements.id</code>. サプリメントID
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.supplements.name</code>. サプリメント名
     */
    public SupplementsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.supplements.name</code>. サプリメント名
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.supplements.created_at</code>.
     */
    public SupplementsRecord setCreatedAt(LocalDateTime value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.supplements.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.supplements.updated_at</code>.
     */
    public SupplementsRecord setUpdatedAt(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.supplements.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SupplementsRecord
     */
    public SupplementsRecord() {
        super(Supplements.SUPPLEMENTS);
    }

    /**
     * Create a detached, initialised SupplementsRecord
     */
    public SupplementsRecord(Integer id, String name, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(Supplements.SUPPLEMENTS);

        setId(id);
        setName(name);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised SupplementsRecord
     */
    public SupplementsRecord(supplement.tables.pojos.Supplements value) {
        super(Supplements.SUPPLEMENTS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetChangedOnNotNull();
        }
    }
}
