#!/bin/sh

# ステージングされたKotlinファイルを取得
files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.kt[s"]\?$')

# ステージングされたファイルがない場合は終了
if [ -z "$files" ]; then
exit 0
fi

# ktlintFormatを実行
echo "Running ktlintFormat..."
./gradlew ktlintFormat

# 修正されたファイルを再度ステージング
git add -u

exit 0
