/*
 * This file is generated by jOOQ.
 */
package supplement.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * サプリメントグループテーブル
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SupplementGroup implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String name;
    private final LocalDateTime createdAt;
    private final LocalDateTime updatedAt;

    public SupplementGroup(SupplementGroup value) {
        this.name = value.name;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public SupplementGroup(
        String name,
        LocalDateTime createdAt,
        LocalDateTime updatedAt
    ) {
        this.name = name;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.supplement_group.name</code>. サプリメントグループ名
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>public.supplement_group.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>public.supplement_group.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SupplementGroup other = (SupplementGroup) obj;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SupplementGroup (");

        sb.append(name);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
